accounts/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    # 회원가입 URL 설정
    path('sign_up/', views.sign_up, name='sign_up'),

    # 로그인 URL 설정
    path('login/', views.login, name='login'),

    # 마이페이지 URL 설정
    path('mypage/', views.mypage, name='mypage'),

    # 로그아웃 URL 설정
    path('logout/', views.logout, name='logout'),
]

ace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings    # 이미지 파일 업로드를 위한 settings import
from django.conf.urls.static import static  # 이미지 파일 업로드를 위한 static import
from travels import views


urlpatterns = [
    # admin 페이지 URL
    path('admin/', admin.site.urls),

    # 메인 index 페이지 URL -> travels 앱의 index View로 연결
    path('', views.index, name="index"),

    # travels로 시작하는 경우, travels 앱의 urls.py로 연결
    path('travels/', include('travels.urls')),

    # posts로 시작하는 경우, posts 앱의 urls.py로 연결
    path('posts/', include('posts.urls')),

    # accounts로 시작하는 경우, accounts 앱의 urls.py로 연결
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  # 이미지 serving를 위해 settings에서 설정한 MEDIA_URL로 요청이 들어올 경우, MEDIA_ROOT 내부에서 검색 후 HTTP Response로 응답

travels/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'travels'

urlpatterns = [
    # Navbar 지도 버튼 클릭 시 URL
    path('map/', views.map, name='map'),

    # Navbar 둘러보기 버튼 클릭 시 URL
    path('spots/', views.spots, name='spots'),

    # 포토스팟 디테일 페이지 URL
    path('spots/<int:travel_id>/', views.spot, name='spot'),

    # 포토스팟 1개 좋아요 URL
    path('spots/<int:travel_id>/like/', views.spotlike, name='spotlike'),

    # 포토스팟 1개 댓글 생성 URL
    path('spots/<int:travel_id>/comment/', views.comment, name='comment'),

    # 포토스팟 1개 댓글 삭제 URL
    path('spots/<int:travel_id>/comment/<int:comment_id>/', views.comment_delete, name="comment_delete")
]

accounts/models.py
import email
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    email = models.EmailField(max_length=100)
    mbti = models.CharField(max_length=50, null=True)
    type = models.CharField(max_length=100)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=50)
    introduce = models.CharField(max_length=100)
    image = models.ImageField(upload_to='accounts', null=True)

    def __str__(self):
        return f'{self.user}'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User  # django에 내장된 User 모델
from django.contrib import auth  # django에 내장된 auth 모델
from .models import Profile


# Create your views here.


# 상백

# 회원가입 기능
def sign_up(request):
    context = {}

    if request.method == 'POST':
        if (request.POST.get('username') and  # 회원가입 시 받은 아이디와 비밀번호 그리고 이메일이 모두 있는지 확인
            request.POST.get('password') and  
            request.POST.get('email') and
            request.POST.get('password') == request.POST.get('password_check')):
            # 그리고 받은 비밀번호와 비밀번호 확인 내용이 일치하는지 확인

            new_user = User.objects.create_user(    # User 모델에 새로운 유저 생성 / 입력된 아이디와 비밀번호로 생성
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )

            auth.login(request, new_user)   # 위에서 생성한 유저를 로그인시키기

            user = request.user                  # 로그인된 유저를 user 변수에 저장 / 밑에 코드들도 회원가입 시 받은 데이터를 각 변수에 저장
            email = request.POST.get('email')
            # age = request.POST.get('age')
            # gender = request.POST.get('gender')
            # image = request.FILES.get('image')
            profile = Profile(user=user, email=email, mbti='none', type='none', age=0, gender='none', introduce='none', image='none')
            profile.save()                       # 각 변수를 Profile 모델 필드에 저장하고 save()

            return redirect('index')

        else:
            context['error'] = '아이디, 비밀번호 그리고 이메일을 다시 입력해주세요!'    


    return render(request, 'accounts/sign_up.html', context)




# 로그인 기능
def login(request):
    context = {}

    if request.method == 'POST':   # POST방식으로 요청되었을 때, username과 password가 모두 입력되었다면 등록된 유저인지 검증진행
        if request.POST.get('username') and request.POST.get('password'):
            user = auth.authenticate(
                request,
                username = request.POST.get('username'),
                password = request.POST.get('password'),
            )

            if user is not None:   # 만약 검증이 되었다면, 로그인 시키기
                auth.login(request, user)
                return redirect('index')
            else:
                context['error'] = '아이디와 비밀번호를 다시 입력해주세요!'  # 검증이 되지 않았다면, error 메세지 보내기
        else:
            context['error'] = '아이디와 비밀번호를 모두 입력해주세요!'      # username과 password가 모두 입력되지 않았다면 error 메세지 보내기        

    return render(request, 'accounts/login.html', context)



# 마이페이지
def mypage(request):

    profile = request.user.profile   # 로그인된 유저의 Profile 모델에 접근

    wishlists = request.user.liked_travels.all()  # 로그인된 유저가 좋아요를 누른 포토스팟 목록

    context = {
        'profile': profile,
        'wishlists': wishlists,
    }

    return render(request, 'accounts/mypage.html', context)


# 로그아웃 기능
def logout(request):
    if request.method == 'POST':
        auth.logout(request)

    return redirect('index')





# 용호




# 영수




# 하은

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'login_style.css' %}">
{% endblock %}

{% block content %}
<div class="login-outer-page">

<div class="login-page">


    <div class="login-box"> 

    <!-- 에러 메세지 띄우기 -->
        <div id="login-error-box">
        {% if error %}
            <div id="login-error" class="alert alert-danger mt-3">
                {{ error }}
            </div>
        {% endif %}
        </div>

        <!-- 로그인 정보 받기 -->
        <form  method="POST" action="{% url 'accounts:login' %}">
                {% csrf_token %}
            <div id="login-form-box">
                <div id="login-form1" class="mb-2 col-lg-3" style="margin-top: 15px;">
                    <label class="form-label" id="id-label" for="username">아이디</label>
                    <input class="form-control" type="text" id="username" name="username" placeholder="아이디 입력">
                </div>

                <div id="login-form2" class="mb-2 col-lg-3" style="margin-top: 15px;">
                    <label class="form-label" id="password-label" for="password">비밀번호</label>
                    <input class="form-control" type="password" id="password" name="password" placeholder="비밀번호 입력">
                </div>

                <button class="btn btn-secondary" type="submit" id="login_button" style="margin-top: 20px"> 로그인 하기</button>
            </div>
        </form>

        <div id="login-blank2">
            <a id="login-blank2" href="{% url 'accounts:sign_up' %}">아직 회원이 아닌가요?</a>
        </div>
    </div>


</div>
<div class="login-blank1"></div>
</div>
{% endblock %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'accounts/mypage_style.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- 프로필 정보 -->
<body id="mypage_container">
    <div class="user_navbar">
        <div class="mypage_header">마이 페이지<span style="color: #ebebeb;"></span></div><br>
        <ul class="user_links">
            <li class="user_info"><span class="user_name" >{{ profile.user }}</span></li>
            <li class="user_info"><span class="user_email" style="font-style: oblique;">{{ profile.email }}</span></li>
        </ul> 
        <!-- <ul class="user_icons" style="display: flex; flex-direction: row;">
            <li class="user_link"><a href="#wishlists"><i class="far fa-heart" ></i></a></li>
            <li class="user_link"><a href="#comments"><i class="fa fa-comment-o" aria-hidden="true"></i></a></li>
        </ul> -->
            <!-- <ul class="social_icons" style="display: flex; flex-direction: row;">
                <li><a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a></li>
                <li><a href="https://www.facebook.com/"><i class="fab fa-facebook-square"></i></a></li>
            </ul> -->
    </div>
    <br>
    <!-- 위시리스트 -->
    <div class="mypage_pages">
    <div id="wishlists" class="mypage_page" >
        <div class="wishlist_liked">LIKED by <span class="highlight" style="font-style: oblique;">@{{ profile.user }}</span></div><br>
        <div class="wishlist_spots">
            {% for wishlist in wishlists %}
            <div class="wishlist_box">
                <!-- <div class="wishlist_title"><a href="{% url 'travels:spot' wishlist.id %}" id="wishlist_click">#{{ wishlist.title }}</a></div> -->
                <img src="{{ wishlist.image.url }}" alt="위시리스트 이미지" class="wishlist_image">
                <div class="image_overlay">
                    <div class="image_title"><a href="{% url 'travels:spot' wishlist.id %}" id="wishlist_click">#{{ wishlist.title }}</a></div>
                </div>
            </div>
            <hr>

            {% endfor %}

            {% endblock %}
        </div>
    </div>  
    </div>

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'sign_up_style.css' %}">
{% endblock %}

{% block content %}

<div class="signup-outer-page">

    <div class="signup-page">
    
    
        <div class="signup-box"> 
    
        <!-- 에러 메세지 띄우기 -->
            <div id="signup-error-box">
            {% if error %}
                <div id="signup-error" class="alert alert-danger mt-3">
                    {{ error }}
                </div>
            {% endif %}
            </div>
    
            <!-- 로그인 정보 받기 -->
            <form method="POST" action="{% url 'accounts:sign_up' %}" enctype="multipart/form-data"> 
                    {% csrf_token %}
                <div id="signup-form-box">
                        <div id="signup-form1" lass="mb-2 col-lg-3">
                            <label  class="form-label" for="username">아이디</label>
                            <input class="form-control" type="text" id="username" name="username" placeholder="아이디">
                        </div>
                
                        <div id="signup-form2" class="mb-2 col-lg-3">
                            <label  style="margin: 0px;" class="form-label" for="password">비밀번호</label>
                            <input class="form-control" type="password" id="password" name="password" placeholder="비밀번호">
                        </div>
                
                        <div id="signup-form3" style="align-items:center; " class="mb-2 col-lg-3">
                            <label style="margin: 0px;" class="form-label" for="password_check">비밀번호 확인</label>
                            <input class="form-control" type="password" id="password_check" name="password_check" placeholder="비밀번호 확인">
                        </div>
                
                        <div id="signup-form4" class="mb-2 col-lg-3">
                            <label style="margin: 0px;" class="form-label" for="email">이메일</label>
                            <input class="form-control" type="email" id="email" name="email" placeholder="이메일">
                        </div>

                        <button class="btn btn-secondary" type="submit" id="signup_button" style="margin-top: 20px"> 회원가입</button>
                    </div>
                    <div id="signup-blank3">
                        <div id="signup-blank2"><a id="signup-blank2" href="{% url 'accounts:login' %}">이미 회원이신가요?</a></div>
                    </div>
                </div>
            </form>
    

        </div>
    
        <div class="signup-blank-bottom"></div>
    </div>
 
    </div>

    <!-- ddddd -->








<!-- 회원가입 정보 받기 -->
<!-- <div class="row">
    <form method="POST" action="{% url 'accounts:sign_up' %}" enctype="multipart/form-data">  
        {% csrf_token %}
        
        <div class="mb-2 col-lg-3">
            <label class="form-label" for="username">아이디</label>
            <input class="form-control" type="text" id="username" name="username" placeholder="아이디">
        </div>

        <div class="mb-2 col-lg-3">
            <label class="form-label" for="password">비밀번호</label>
            <input class="form-control" type="password" id="password" name="password" placeholder="비밀번호">
        </div>

        <div class="mb-2 col-lg-3">
            <label class="form-label" for="password_check">비밀번호 확인</label>
            <input class="form-control" type="password" id="password_check" name="password_check" placeholder="비밀번호 확인">
        </div>

        <div class="mb-2 col-lg-3">
            <label class="form-label" for="email">이메일</label>
            <input class="form-control" type="email" id="email" name="email" placeholder="이메일">
        </div> -->

        <!-- <div class="mb-2 col-lg-3">
            <label class="form-label" for="age">나이</label>
            <input class="form-control" type="number" id="age" name="age" placeholder="나이">
        </div>

        <div class="mb-2 col-lg-3">
            <p class="mt-3">성별</p>
            <input type="checkbox" id="gender" name="gender" value="남자">
            <label class="form-label" for="gender">남</label>
            <input type="checkbox" id="gender" name="gender" value="여자">
            <label class="form-label" for="gender">여</label>
        </div>

        <div class="mb-2 col-lg-3">
            <label class="form-label" for="image">프로필 사진</label>
            <input class="form-control" type="file" id="image" name="image" placeholder="프로필 사진 업로드">
        </div> -->

        <!-- <div class="mb-2">
            <button type="submit">회원가입</button>
        </div>

    </form>
</div> -->


{% endblock %}