accounts/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    # 회원가입 URL 설정
    path('sign_up/', views.sign_up, name='sign_up'),

    # 로그인 URL 설정
    path('login/', views.login, name='login'),

    # 마이페이지 URL 설정
    path('mypage/', views.mypage, name='mypage'),

    # 로그아웃 URL 설정
    path('logout/', views.logout, name='logout'),
]

ace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings    # 이미지 파일 업로드를 위한 settings import
from django.conf.urls.static import static  # 이미지 파일 업로드를 위한 static import
from travels import views


urlpatterns = [
    # admin 페이지 URL
    path('admin/', admin.site.urls),

    # 메인 index 페이지 URL -> travels 앱의 index View로 연결
    path('', views.index, name="index"),

    # travels로 시작하는 경우, travels 앱의 urls.py로 연결
    path('travels/', include('travels.urls')),

    # posts로 시작하는 경우, posts 앱의 urls.py로 연결
    path('posts/', include('posts.urls')),

    # accounts로 시작하는 경우, accounts 앱의 urls.py로 연결
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  # 이미지 serving를 위해 settings에서 설정한 MEDIA_URL로 요청이 들어올 경우, MEDIA_ROOT 내부에서 검색 후 HTTP Response로 응답

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    # Navbar 함께하기 버튼 클릭 시 URL
    path('', views.index, name='index'),

    # 게시판 디테일 페이지 URL
    path('<int:post_id>/', views.detail, name='detail'),

    # 게시판 디테일 페이지 댓글 생성
    path('<int:post_id>/comment/', views.comment, name='comment'),

    # 게시판 디테일 페이지 댓글 삭제
    path('<int:post_id>/comment/<int:comment_id>/', views.comment_delete, name='comment_delete'),

    # 게시판 글 생성하기 
    path('create/', views.create, name='create'),

    # 게시판 글 수정하기
    path('<int:post_id>/edit/', views.edit, name='edit'),

    # 게시판 글 삭제하기
    path('<int:post_id>/delete/', views.delete, name='delete'),
]

travels/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'travels'

urlpatterns = [
    # Navbar 지도 버튼 클릭 시 URL
    path('map/', views.map, name='map'),

    # Navbar 둘러보기 버튼 클릭 시 URL
    path('spots/', views.spots, name='spots'),

    # 포토스팟 디테일 페이지 URL
    path('spots/<int:travel_id>/', views.spot, name='spot'),

    # 포토스팟 1개 좋아요 URL
    path('spots/<int:travel_id>/like/', views.spotlike, name='spotlike'),

    # 포토스팟 1개 댓글 생성 URL
    path('spots/<int:travel_id>/comment/', views.comment, name='comment'),

    # 포토스팟 1개 댓글 삭제 URL
    path('spots/<int:travel_id>/comment/<int:comment_id>/', views.comment_delete, name="comment_delete")
]

travels/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
from posts.models import Post

# Create your models here.

class Travel(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=50)
    region = models.CharField(max_length=100)
    address = models.CharField(max_length=200, null=True, default=1)
    short_content = models.CharField(max_length=50)
    long_content = models.CharField(max_length=100)
    hashtag = models.CharField(max_length=200, default=1)
    image = models.ImageField(upload_to='travels', null=True)
    image_second = models.ImageField(upload_to='travels', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    liked_users = models.ManyToManyField(User, related_name='liked_travels')
    latitude = models.FloatField(default=0.0)
    longitude = models.FloatField(default=0.0)

    def __str__(self):
        return f'{self.id} {self.title}'


class Comment(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    travel = models.ForeignKey(Travel, on_delete=models.CASCADE, null=True, related_name='travel_comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, related_name='post_comments')
    secret = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.author} {self.travel} {self.post}'

travels/views.py
from multiprocessing import context
from django.shortcuts import get_object_or_404, render, redirect
from .models import Travel, Comment
from django.db.models import Q  # 모델 filter를 하기 위해 import
import requests # API HTTP Request 전송을 하기 위해 requests 라이브러리 import
from django.contrib.auth.decorators import login_required # 로그인된 유저만 접근할 수 있도록 import
from accounts.models import Profile
from django.utils import timezone
import random
from django.db.models import Count

# Create your views here.


# 상백



##### github 수정

# 메인페이지
# 아래에 영수 수정


# 둘러보기 페이지
def spots(request):
    listtype = request.GET.get('listtype', '')  # listtype이라는 이름으로 GET방식으로 보낸 데이터를 저장

    if listtype == '최신순':
        travels = Travel.objects.all().order_by('-id')  # Travel 모델 pk 기준 내림차순으로 데이터 정렬하기(최신순)
    elif listtype == '인기순':
        travels = Travel.objects.annotate(like=Count('liked_users__liked_travels')).order_by('-like', '-id')
        # 좋아요순으로 내림차순 / 좋아요 개수가 같으면 id 내림차순으로 설정  
    else:
        travels = Travel.objects.all()  # Travel 모델 데이터 전부 다 travels라는 변수에 저장


    locationsearch = request.GET.get('locationsearch', '')  # locationsearch라는 이름으로 GET방식으로 보낸 데이터를 저장

    if locationsearch == '제주전체':                          # 데이터 value에 따라 Travel 모델 필드값을 필터링해서 보여주기
        travels = Travel.objects.all().filter(location__icontains='jeju')
    elif locationsearch == '제주시':
        travels = Travel.objects.all().filter(region__icontains='제주시')    
    elif locationsearch == '한림읍':
        travels = Travel.objects.all().filter(region__icontains='한림읍')
    elif locationsearch == '한경면':
        travels = Travel.objects.all().filter(region__icontains='한경면')
    elif locationsearch == '안덕면':
        travels = Travel.objects.all().filter(region__icontains='안덕면')
    elif locationsearch == '성산읍':
        travels = Travel.objects.all().filter(region__icontains='성산읍')
    elif locationsearch == '남원읍':
        travels = Travel.objects.all().filter(region__icontains='남원읍')    
    elif locationsearch == '애월읍':
        travels = Travel.objects.all().filter(region__icontains='애월읍') 
    elif locationsearch == '구좌읍':
        travels = Travel.objects.all().filter(region__icontains='구좌읍')      
                       

    q = request.GET.get('query', '')  # 검색창에서 검색한 값은 query라는 이름으로 정했고 GET방식으로 보낸 데이터를 저장

    if q:
        travels = Travel.objects.all().filter(title__icontains=q)  # 포토스팟 제목에 해당 데이터가 들어있으면 보여주기   



    context = {
        'listtype': listtype,
        'locationsearch': locationsearch,
        'q': q,
        'travels': travels,
    }

    return render(request, 'travels/spots.html', context)



# 포토스팟 좋아요 기능
@login_required
def spotlike(request, travel_id):
    
    if request.method == 'POST':
        try:
            travel = Travel.objects.get(id=travel_id)

            if request.user in travel.liked_users.all():
                travel.liked_users.remove(request.user)
            else:
                travel.liked_users.add(request.user)


            return redirect('travels:spots')
        except Travel.DoesNotExist:
            pass        

    elif request.method == 'GET':
        try:
            travel = Travel.objects.get(id=travel_id)

            if request.user in travel.liked_users.all():
                travel.liked_users.remove(request.user)
            else:
                travel.liked_users.add(request.user)


            return redirect('travels:spot', travel_id=travel.id)
        except Travel.DoesNotExist:
            pass        

        
    redirect('travels:spots')




# 포토스팟 디테일 페이지
def spot(request, travel_id):

    travel = Travel.objects.get(id=travel_id)   # 해당 travel_id 데이터를 조회해서 travel이라는 변수에 저장
    

    # 지도 API 기능
    search = travel.address
    url = 'https://dapi.kakao.com/v2/local/search/address.json?query={}'.format(search)
    result = requests.get(url, headers={"Authorization" : "KakaoAK 537c71004ec6bb642b90b8bdf96180e5"})
    result_dictionary = result.json()
    documents = result_dictionary.get('documents')


    context = {
        'search': search,
        'travel': travel,
        'documents': documents,
    }

    return render(request, 'travels/spot.html', context)


# 포토스팟 디테일 페이지 댓글 생성
def comment(request, travel_id):
    if request.method == 'POST':
        author = request.user
        comment_profile = Profile.objects.get(user=author)

        content = request.POST.get('content')

        travel = Travel.objects.get(id=travel_id)

        if not content:
            return redirect('travels:spot', travel_id=travel.id)
        
        Comment.objects.create(author=comment_profile, content=content, created_at=timezone.now(), travel=travel)

    return redirect('travels:spot', travel_id=travel.id)



# 포토스팟 디테일 페이지 댓글 삭제
def comment_delete(request, travel_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    travel = Travel.objects.get(id=travel_id)

    comment.delete()

    return redirect('travels:spot', travel_id=travel.id)




# 용호
def map(request):

    if request.user.is_authenticated:
        if request.method == 'POST':
            selected = request.POST.get('selected')
            if selected == "1":
                spots = request.user.liked_travels.all()
                print(selected)
            elif selected == "2":
                spots = Travel.objects.all()
                print(selected)
            else:
                spots = Travel.objects.all()

        else:
            spots = Travel.objects.all()

        # Travel이라는 모델 데이터베이스에 저장된 데이터 가져오기

        context ={
    
            'spots': spots,

        }

    else:
        if request.method == 'POST':
            selected = request.POST.getlist('selected')
            

        spots = Travel.objects.all()

        # Travel이라는 모델 데이터베이스에 저장된 데이터 가져오기

        context ={
    
            'spots': spots,

        }

    return render(request, 'travels/map.html', context)




# 영수

# 메인페이지 
def index(request):
    spots = list(Travel.objects.all())
    spots = random.sample(spots, 6)
    
    context = {
        'spots': spots,

    }

    return render(request, 'travels/index.html', context)



# 하은

travels/templates/travels/index.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
    <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" href="{% static 'index_style.css' %}">
    <style>.slick-sample{width: 100%;height: 200px;} .slick-sample .slick-list{height: 100%;} </style>

{% endblock %}


{% block content %}

<div class="index-page">
    <div class="index-page-inner">
        <div class="index-first-page">
            <div class="index-text1"><a href="{% url 'travels:spots' %}" style="text-decoration-line: none"><div class="index-text">여기선 대충 찍어도 <span style="color:#FC6067">인생샷</span>,</div></a></div>
            <!--캐러셀 만들기 -->
            <div class="post-slider">       
                <i class="fas fa-caret-left prev"></i>
                <i class="fas fa-caret-right next"></i>  
                <div class="post-wrapper">
                    {% for spot in spots %}
                        <div class="post">
                            <a href="{% url 'travels:spot' spot.id %}" style="text-decoration:none;">
                                <div class="index-spots-title">
                                    <p><i class="fas fa-heart" style="color:#FC6067"></i>
                                        <br>{{ spot.liked_users.count }}</p></div>
                                <img class="index-spots-image" src="{{ spot.image.url }}" style="box-shadow:5px 5px 10px rgba(0, 0, 0, 0.4);">
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!--post slider-->
            <div class="index-text2"><a href="{% url 'posts:index' %}" style="text-decoration-line: none"><div class="index-text">영혼 담아 찍어 줄 <span >동행</span>과 함께</div></a></div>
        </div>
    </div>
</div>

<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<script> 
    $('.post-wrapper').slick({
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 2000,
    nextArrow:$('.next'),
    prevArrow:$('.prev'),
    });
</script>



{% endblock %}

travels/templates/travels/map.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'travels/map_style.css' %}">
{% endblock %}


{% block content %}
<!-- <h1>포토스팟 찾기</h1> -->
<div class="map-page">

  <div class="map-like-filter">

    {%if user.is_authenticated %}

    <form class="map-like-filter-form" action="" method="post">
      {%csrf_token%}
      <label class="map-filter-label"><input type="radio" autocomplete="off" name="selected" id="selected" value="1">
        <p id="map-filter-title">좋아하는 스팟</p>
      </label>
      <label class="map-filter-label"><input type="radio" autocomplete="off" name="selected" id="selected" value="2">
        <p id="map-filter-title">전체 스팟</p>
      </label>
      <button class="btn btn-secondary" id="map-filter-button" type="submit">모아보기</button>


    </form>

    {% else %}
    <div>
      <a id="map-login" href="{% url 'accounts:login' %}">로그인하고 좋아하는 스팟만 모아보세요!</a>
    </div>
    {%endif%}

  </div>

  <div class="map-container">

    <div id="map" style="width:790px; height:100%; border-radius: 5%;"></div>

    <div id="card">
      <div id="card_image">
        <a id="btn_a" href="/travels/map/">
          <div id="card_hover_text">
            <p></p>
          </div>
          <img id="image_test" src="/media/travels/default_image.jpg" alt="default_image">
        </a>
      </div>

      <div id="card_info-container">
        <div id="card_info">
          <div id="card_region"></div>
          <div id="card_title"></div>
          <div id="card_hashtag"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="lat" style="display:none">
  {% for re in spots %}
  {{ re.latitude}},
  {% endfor %}
</div>

<div id="lng" style="display:none">
  {% for re in spots %}
  {{ re.longitude}},
  {% endfor %}
</div>

<div id="name" style="display:none">
  {% for re in spots %}
  {{ re.title}},
  {% endfor %}
</div>

<div id="region" style="display:none">
  {% for re in spots %}
  {{ re.region}},
  {% endfor %}
</div>

<div id="hashtag" style="display:none">
  {% for re in spots %}
  {{ re.hashtag}},
  {% endfor %}
</div>

<div id="image" style="display:none">
  {% for re in spots %}
  {{ re.image.url}},
  {% endfor %}
</div>

<div id="id" style="display: none;">
  {% for re in spots %}
  {{ re.id}},
  {% endfor %}
</div>

<div id="address" style="display: none;">
  {% for re in spots %}
  {{ re.address }},
  {% endfor %}
</div>

<div id="shortContent" style="display: none;">
  {% for re in spots %}
  {{ re.short_content}},
  {% endfor %}
</div>

<script type="text/javascript"
  src="//dapi.kakao.com/v2/maps/sdk.js?appkey=7017ebc62c378fa5ebb089d1fd591804&libraries=services,clusterer,drawing"></script>
<script>
  var mapContainer = document.getElementById('map'), // 지도를 표시할 div  
    mapOption = {
      center: new kakao.maps.LatLng(33.3803481250219, 126.54526877357988), // 지도의 중심좌표
      level: 10// 지도의 확대 레벨
    };

  var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

  // 마커를 표시할 위치와 title 객체 배열입니다 

  var list_lat = document.getElementById("lat").innerText.split(',');
  var list_lng = document.getElementById("lng").innerText.split(',');
  var list_name = document.getElementById("name").innerText.split(',');
  var list_image = document.getElementById("image").innerText.split(',');
  var list_hashtag = document.getElementById("hashtag").innerText.split(',');
  var list_id_number = document.getElementById("id").innerText.split(',');
  var list_address = document.getElementById("address").innerText.split(',');
  var list_shortContent = document.getElementById("shortContent").innerText.split(',');
  var list_region = document.getElementById("region").innerText.split(',');

  var positions = new Array();
  var id_array = [];
  var location_name = [];

  for (var i = 0; i < list_lat.length; i++) {
    var latitude = list_lat[i];
    var longitude = list_lng[i];
    var number = list_id_number[i];
    var name = list_name[i];
    var address = list_address[i];
    var region = list_region[i];

    positions.push(new kakao.maps.LatLng(latitude, longitude));
    id_array.push(number);
    location_name.push(name);
  }

  // 마커 이미지의 이미지 주소입니다
  var imageSrc = "/static/images/pin.png";

  for (var i = 0; i < positions.length; i++) {

    // 마커 이미지의 이미지 크기 입니다
    var imageSize = new kakao.maps.Size(20, 25);

    // 마커 이미지를 생성합니다    
    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize);

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
      map: map, // 마커를 표시할 지도
      position: positions[i], // 마커를 표시할 위치
      image: markerImage, // 마커 이미지 
    });

    var iwContent = "<div style='height:60px; width:300px;'>" + list_id_number[i] + list_name[i] + "</br>" + list_hashtag[i] + "</div>" + "<img style='height: 300px; width:300px;' src=" + list_image[i] + ">";

    const test_title = list_name[i];
    const test_image = list_image[i];
    const test_content = list_shortContent[i];
    const test_hashtag = list_hashtag[i];
    const test_id = list_id_number[i];
    const test_address = list_address[i];
    const id = test_id.replace(/\s*/g, "");
    const test_region = list_region[i];

    var infoWindow = new kakao.maps.InfoWindow({
      content: iwContent
    });

    (function (marker, infoWindow) {
      // kakao.maps.event.addListener(marker, 'mouseover', function () {
      //   infoWindow.open(map, marker);
      // })
      // kakao.maps.event.addListener(marker, 'mouseout', function () {
      //   infoWindow.close();
      // })

      kakao.maps.event.addListener(marker, 'click', function () {
        //console.log(marker);
        document.getElementById('card_title').innerHTML = test_title;
        document.getElementById('card_title').src = '/media/travels/cheveron.png';
        document.getElementById('image_test').src = test_image;
        document.getElementById('card_hashtag').innerHTML = test_hashtag;
        document.getElementById('btn_a').href = '/travels/spots/' + id + '/';
        document.getElementById('card_region').innerHTML = test_region;
      })
    })(marker, infoWindow);

    marker.setMap(map);
  }

</script>
</div>
{% endblock %}

travels/templates/travels/spot.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" href="{% static 'travels/spot_style.css' %}">
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    <style>.slick-sample{width: 100%;height: 200px;} .slick-sample .slick-list{height: 100%;} </style>
{% endblock %}


{% block content %}
<div class="spot-page">
    <div class="spot-inner-page">
        <div class="spot-container1">
            <div class="spot-pics">
                <div class="post-slider">       
                    <i class="fas fa-caret-left prev"></i>
                    <i class="fas fa-caret-right next"></i>  
                    <div class="post-wrapper">
                            <div class="post">
                                <img class="index-spots-image" src="{{ travel.image.url }}">
                            </div>
                            <div class="post">
                                <img class="index-spots-image" src="{{ travel.image_second.url }}">
                            </div>
                    </div>
                </div>
            </div>
            <div class="spot-container1-1">
                <div class="spot-info">
                    <div id="spot-title">{{ travel.title }}</div>
                    <div class="spot-info-text"><span class="spot-category">지역 |</span> {{ travel.region }}</div>
                    <div class="spot-info-text"><span class="spot-category">주소 |</span> {{ travel.address }}</div>
                    <div class="spot-info-text"></br></div>
                    <div id="short-text" class="spot-info-text">"{{ travel.short_content }}"</div>
                    <div id="hashtag-text" class="spot-info-text">{{ travel.hashtag }}</div>

                </div>


                <div class="spot-like">
                    <a href="{% url 'posts:index' %}" style="text-decoration: none;" id="board_connect">{{ travel.title }}, 함께갈 사람들을 찾아보세요!</a>
                    <div class="spot-counts">
                        <div class="spot-count">
                            <i id="spot-comment" class="fas fa-comment-dots"></i><span id="short-text-count">{{ travel.travel_comments.count }}</span>
                        </div>
                        <div class="spot-count">
                            <form method="GET" action="{% url 'travels:spotlike' travel.id %}">
                                {% if user in travel.liked_users.all %}
                                <button type="submit" id="like_heart"><i id="spotlike1" class="fas fa-heart"> <span id="short-text-count" > {{ travel.liked_users.count }}</span></i></button>
                                {% else %}
                                <button type="submit" id="like_heart"><i id="spotlike2" class="fas fa-heart"> <span id="short-text-count"> {{ travel.liked_users.count }}</span></i></button>
                                {% endif %}
                            </form>  
                        </div>
                    </div>
                </div>    

            </div>    
        </div>

        <div class="spot-container2">
            <p class="photospot_information">{{ travel.long_content }}</p>
            
        </div>
        <div class="spot-container3">
            <div id="map" style="width:100%;height:500px; margin-bottom: 50px;  border-radius: 5%; "></div>
        <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=7017ebc62c378fa5ebb089d1fd591804&libraries=services,clusterer,drawing"></script>
        <script>
            var container = document.getElementById('map');
            var options = {
                center: new kakao.maps.LatLng(33.450701, 126.570667),
                level: 9
            };
    
            var map = new kakao.maps.Map(container, options);  // 지도를 생성합니다



            var imageSrc = "/static/images/pin.png", // 마커이미지의 주소입니다    
                imageSize = new kakao.maps.Size(50, 50), // 마커이미지의 크기입니다
                imageOption = {offset: new kakao.maps.Point(27, 30)}; // 마커이미지의 옵션입니다. 마커의 좌표와 일치시킬 이미지 안에서의 좌표를 설정합니다.

            // 마커의 이미지정보를 가지고 있는 마커이미지를 생성합니다
            var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption)    




            // 주소-좌표 변환 객체를 생성합니다
            var geocoder = new kakao.maps.services.Geocoder();

            // 주소로 좌표를 검색합니다
            geocoder.addressSearch('"제주도" + {{ search }}', function(result, status) {

                // 정상적으로 검색이 완료됐으면 
                if (status === kakao.maps.services.Status.OK) {

                    var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                    // 결과값으로 받은 위치를 마커로 표시합니다
                    var marker = new kakao.maps.Marker({
                        map: map,
                        position: coords,
                        image: markerImage, // 마커이미지 설정 
                    });

                    // 인포윈도우로 장소에 대한 설명을 표시합니다

                    // django template language를 javascript 안에서 사용하려면 이렇게 '' 작은따옴표를 사용해보자
                    '{% for document in documents %}' 
                    var infowindow = new kakao.maps.InfoWindow({
                        content: '<div style="width:320px;text-align:center;padding:10px 0;">{{ document.address_name }}</div>'
                    });
                    infowindow.open(map, marker);
                    '{% endfor %}'
                    // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                    map.setCenter(coords);
                } 
            });    
        </script>
        </div>
        <div class="spot-container4">
            <!-- 댓글 기능 -->

    <div class="row" id="photospot_comment">
            <div class="spot-review">Review</div>
            <div>
                {% for comment in travel.travel_comments.all %}
                    <div style="margin-top:20px;">
                        <p>{{ comment.author }} | <span>{{ comment.created_at }}</span></p>
                        <p>{{ comment.content }}</p>        
                    
                    <!-- 댓글 삭제 버튼 -->
                    {% if user == comment.author.user %}
                        <a href="{% url 'travels:comment_delete' travel.id comment.id %}"><button id="comment_delete" type="submit" name="delete">삭제</button></a>
                    {% endif %}
                    </div>
                    
                    <hr>
                {% endfor %}
            </div>
            <!-- 댓글 생성 -->
            <div  class="mb-3">
                <form  id="comment-box" method="POST" action="{% url 'travels:comment' travel.id %}">
                    {% csrf_token %}
                    <textarea class="form-control" id="comment-area" name="content"  cols="115" rows="5" placeholder="새로운 후기를 남겨주세요:)"></textarea>
                    <button class="btn btn-secondary" type="submit" id="comment_button" style="margin-bottom: 20px;">후기 남기기</button>
                </form>
            </div>

        </div>
    </div>


        </div>
    </div>
</div>







<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<script> 
    $('.post-wrapper').slick({
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 2000,
    nextArrow:$('.next'),
    prevArrow:$('.prev'),
    dots: true,
    infinite: true,
    speed: 500,
    fade: true,
    cssEase: 'linear',
    dotsClass : "slick-dots",  
    });
</script>



{% endblock %}

travels/templates/travels/travels.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'travels/travels_style.css' %}">
{% endblock %}

{% block content %}
<h1>여행 검색 페이지</h1>

{% for travel in travels %}
<p>여행 title : {{ travel.title }}</p>
<p>{{ travel.short_content }}</p>
<p><img id="travel-image" src="{{ travel.image.url }}" alt="여행 이미지"></p>

{% endfor %}

{% endblock %}