accounts/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    # 회원가입 URL 설정
    path('sign_up/', views.sign_up, name='sign_up'),

    # 로그인 URL 설정
    path('login/', views.login, name='login'),

    # 마이페이지 URL 설정
    path('mypage/', views.mypage, name='mypage'),

    # 로그아웃 URL 설정
    path('logout/', views.logout, name='logout'),
]

ace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings    # 이미지 파일 업로드를 위한 settings import
from django.conf.urls.static import static  # 이미지 파일 업로드를 위한 static import
from travels import views


urlpatterns = [
    # admin 페이지 URL
    path('admin/', admin.site.urls),

    # 메인 index 페이지 URL -> travels 앱의 index View로 연결
    path('', views.index, name="index"),

    # travels로 시작하는 경우, travels 앱의 urls.py로 연결
    path('travels/', include('travels.urls')),

    # posts로 시작하는 경우, posts 앱의 urls.py로 연결
    path('posts/', include('posts.urls')),

    # accounts로 시작하는 경우, accounts 앱의 urls.py로 연결
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  # 이미지 serving를 위해 settings에서 설정한 MEDIA_URL로 요청이 들어올 경우, MEDIA_ROOT 내부에서 검색 후 HTTP Response로 응답

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    # Navbar 함께하기 버튼 클릭 시 URL
    path('', views.index, name='index'),

    # 게시판 디테일 페이지 URL
    path('<int:post_id>/', views.detail, name='detail'),

    # 게시판 디테일 페이지 댓글 생성
    path('<int:post_id>/comment/', views.comment, name='comment'),

    # 게시판 디테일 페이지 댓글 삭제
    path('<int:post_id>/comment/<int:comment_id>/', views.comment_delete, name='comment_delete'),

    # 게시판 글 생성하기 
    path('create/', views.create, name='create'),

    # 게시판 글 수정하기
    path('<int:post_id>/edit/', views.edit, name='edit'),

    # 게시판 글 삭제하기
    path('<int:post_id>/delete/', views.delete, name='delete'),
]

travels/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'travels'

urlpatterns = [
    # Navbar 지도 버튼 클릭 시 URL
    path('map/', views.map, name='map'),

    # Navbar 둘러보기 버튼 클릭 시 URL
    path('spots/', views.spots, name='spots'),

    # 포토스팟 디테일 페이지 URL
    path('spots/<int:travel_id>/', views.spot, name='spot'),

    # 포토스팟 1개 좋아요 URL
    path('spots/<int:travel_id>/like/', views.spotlike, name='spotlike'),

    # 포토스팟 1개 댓글 생성 URL
    path('spots/<int:travel_id>/comment/', views.comment, name='comment'),

    # 포토스팟 1개 댓글 삭제 URL
    path('spots/<int:travel_id>/comment/<int:comment_id>/', views.comment_delete, name="comment_delete")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <!-- CSS 파일 연동 -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block style %}
    {% endblock %}
    <!-- Bootstrap CSS 연동 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- kopub font 연결 -->
    <link href="https://webfontworld.github.io/kopus/KoPubWorldDotum.css" rel="stylesheet">
    <!-- 구글폰트 연결 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <!-- favicon -->
    <link rel="shortcut icon" href="/static/images/logo_fav.ico" type="image/x-icon">
    <link rel="icon" href="/static/images//logo_fav.ico" type="image/x-icon">
    <!-- fontawesome 연결 -->
    <script src="https://kit.fontawesome.com/8a5f5a589a.js" crossorigin="anonymous"></script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spot On!</title>
</head>
<body>

<div class="nav-all"> 
  <div class="nav-logo">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img id="logo" src="/static/images/logo (6).png">
      <span id="logo-text">Spot On</span>
    </a>
  </div>
  <div class="nav-menu">
    <a id="menu1" class="menu-box" aria-current="page" href="{% url 'travels:spots' %}"><i id="menu1" class="fas fa-image"></i>
      둘러보기</a>
    <a id="menu2" class="menu-box" aria-current="page" href="{% url 'travels:map' %}"><i id="menu2" class="fas fa-map-marked-alt"></i>
      지도</a>
    <a id="menu3" class="menu-box" aria-current="page" href="{% url 'posts:index' %}"><i id="menu3" class="fas fa-user-friends"></i>
      함께하기</a>
  </div>

  <div class="nav-login">
    {% if user.is_authenticated %}
      <div class="nav-login-item">
        {{ user.username }}님, 안녕하세요.
      </div>
      <div class="nav-login-box">
        <div class="nav-login-item">
          <a class="link" aria-current="page" href="{% url 'accounts:mypage' %}">마이페이지</a>
        </div>
        <div>
          &nbsp; |   &nbsp;         
        </div>
        <div class="nav-login-item">
          <form method="POST" action="{% url 'accounts:logout' %}">
          {% csrf_token %}
            <button id="logout_button" type="submit">  로그아웃</button>
          </form>
        </div>
      </div>

    {% else %}
    <!-- 로그인 & 회원가입 버튼 -->
    <div class="nav-login-box">
      <div class="nav-login-item">
        <a class="link"  aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
      </div>
      <div>
        &nbsp; |   &nbsp;         
      </div>
      <div class="nav-login-item">
        <a class="link"  aria-current="page" href="{% url 'accounts:sign_up' %}">회원가입</a>
      </div>
    </div>
    {% endif %}
  </div>
</div>
    {% block content %}
    {% endblock %} 

<!-- Bootstrap Javascript 연동 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    
</body>
</html>

