ace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings    # 이미지 파일 업로드를 위한 settings import
from django.conf.urls.static import static  # 이미지 파일 업로드를 위한 static import
from travels import views


urlpatterns = [
    # admin 페이지 URL
    path('admin/', admin.site.urls),

    # 메인 index 페이지 URL -> travels 앱의 index View로 연결
    path('', views.index, name="index"),

    # travels로 시작하는 경우, travels 앱의 urls.py로 연결
    path('travels/', include('travels.urls')),

    # posts로 시작하는 경우, posts 앱의 urls.py로 연결
    path('posts/', include('posts.urls')),

    # accounts로 시작하는 경우, accounts 앱의 urls.py로 연결
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  # 이미지 serving를 위해 settings에서 설정한 MEDIA_URL로 요청이 들어올 경우, MEDIA_ROOT 내부에서 검색 후 HTTP Response로 응답

posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    # Navbar 함께하기 버튼 클릭 시 URL
    path('', views.index, name='index'),

    # 게시판 디테일 페이지 URL
    path('<int:post_id>/', views.detail, name='detail'),

    # 게시판 디테일 페이지 댓글 생성
    path('<int:post_id>/comment/', views.comment, name='comment'),

    # 게시판 디테일 페이지 댓글 삭제
    path('<int:post_id>/comment/<int:comment_id>/', views.comment_delete, name='comment_delete'),

    # 게시판 글 생성하기 
    path('create/', views.create, name='create'),

    # 게시판 글 수정하기
    path('<int:post_id>/edit/', views.edit, name='edit'),

    # 게시판 글 삭제하기
    path('<int:post_id>/delete/', views.delete, name='delete'),
]

posts/models.py
from email.policy import default
from django.db import models
from accounts.models import Profile

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    due = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'

posts/views.py
from multiprocessing import context
from django.shortcuts import get_object_or_404, render, redirect
from .models import Post
from travels.models import Comment, Travel
from accounts.models import Profile
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.


# 상백

# 게시판 리스트
def index(request):
 
   posts = Post.objects.all().order_by('-id')    # Post 모델 데이터 전부를 조회해서 posts 변수에 저장
   

   # 페이지네이터 코드
   paginator = Paginator(posts, 10)
   page = request.GET.get('page')
   posts_page = paginator.get_page(page)

   page_range = paginator.page_range



   # 검색 기능
   q = request.GET.get('query', '')
   if q:
       posts_page = Post.objects.all().filter(title__icontains=q)


   
   context = {
       'posts': posts,
       'page_range': page_range,
       'posts_page': posts_page,
       'q': q,
   }
  
   return render(request, 'posts/posts.html', context)
 
 
 
# 게시판 디테일 페이지
def detail(request, post_id):
   
 
   post = Post.objects.get(id=post_id)   # Posts 모델 데이터 1개 조회 후 post 변수에 저장
   
    
   context = {
       'post': post,
   }
 
   return render(request, 'posts/detail.html', context)
 
 
 
# 게시판 디테일 페이지 댓글
@login_required
def comment(request, post_id):
    
   if request.method == 'POST':
        user = request.user
        author = Profile.objects.get(user=user)
    
        content = request.POST.get('content')
        post = Post.objects.get(id=post_id)
        
        secret = request.POST.get('secret_comment', 'False')
    
        comment = Comment(author=author, content=content, created_at=timezone.now(), post=post, secret=secret)
        comment.save()

        return redirect('posts:detail', post_id=post.id)
   return redirect('posts:detail', post_id=post.id)  
    


 
                


# 게시판 디테일 페이지 댓글 삭제
def comment_delete(request, post_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post = Post.objects.get(pk=post_id)

    comment.delete()

    return redirect('posts:detail', post_id=post.id)



# 게시판 글 생성하기
@login_required
def create(request):
    travels = Travel.objects.all()

    if request.method == 'POST':
        user = request.user
        user = Profile.objects.get(user=user)
        title = request.POST.get('title')
        body = request.POST.get('body')
        # due = request.POST.get('due')
        # location = request.POST.get('photospot')

        post = Post(user=user, title=title, body=body, location='none')
        post.save()

        return redirect('posts:index')

    context = {
        'travels': travels,
    }

    return render(request, 'posts/create.html', context)


# 게시판 글 수정하기
@login_required
def edit(request, post_id):

    try:
        post = Post.objects.get(id=post_id, user=request.user.profile)   # 본인일 경우에만 수정할 수 있도록 설정
        travels = Travel.objects.all()
    except Post.DoesNotExist:
        return redirect('posts:index')

    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.body = request.POST.get('body')
        # post.due = request.POST.get('due')
        # post.location = request.POST.get('photospot')
        post.save()

        return redirect('posts:detail', post_id=post.id)

    context = {
        'post': post,
        'travels': travels,
    }

    return render(request, 'posts/edit.html', context)


# 게시판 글 삭제하기
@login_required
def delete(request, post_id):

    try:
        post = Post.objects.get(id=post_id, user=request.user.profile)
        post.delete()
    except Post.DoesNotExist:
        return redirect('posts:index')     

    return redirect('posts:index')


# 용호




# 영수




# 하은

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'posts/create_style.css' %}">
{% endblock %}

{% block content %}
<div class="col-lg-12 col-md-12 col-sm-12" id="create_container">
    <h1 id="create_title">글 작성하기</h1>

    <!-- 글 작성 div -->
    <div class="write_container"> 
        <form method="POST" action="{% url 'posts:create' %}">
            {% csrf_token %}

            <!-- 지역 선택 및 등록 버튼 -->
            <div>
                <!-- <select id="select_photospot" name="photospot" required>
                    <option value="" disabled selected>포토스팟 선택</option>
                    {% for travel in travels %}
                    <option value="{{ travel.title }}">{{ travel.title }}</option>
                    {% endfor %}
                </select> -->
            
                <button id="write_submit" type="submit">등록</button>
            </div>

            <!-- 글 작성 정보 받기 -->
            <div class="mb-4">
                <input type="text" class="form-control" id="title" name="title" placeholder="제목을 입력해주세요.">
            </div>
            <div class="mb-3">
                <textarea class="form-control" id="body" rows="5" name="body" placeholder="내용을 입력해주세요."></textarea>
            </div>
            <!-- <div class="mb-3">
                <label for="due">기한 설정하기</label>
                <input type="date" class="form-control" id="due" name="due" style="margin-top: 10px;">
            </div> -->

        </form>
    </div>    
</div>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'detail_style.css' %}">
{% endblock %}

{% block content %}
<div class="post-page">
    <div class="detail_container">
        {% if post %}
        <!-- 게시글 제목 -->
        <div class="title_container">
            <h1 id="detail_title">{{ post.title }}</h1>
            <!-- <h2 id="detail_due">Due : {{ post.due|date:'Y-m-d' }}</h2>
       <h2 id="detail_photospot">포토스팟 : {{ post.location }}</h2> -->
        </div>
        <!-- 게시글 유저와 생성일 -->
        <div class="user_info_container">
            <ul class="user_info">
                <li class="user_info_li_1"><span id="user_info_title">작성자 </span> {{ post.user }}</li>
                <li class="user_info_li_2"><span id="user_info_title">작성일</span> {{ post.created_at|date:'Y-m-d H:i:s'}}</li>
            </ul>
        </div>

        <!-- 게시글 내용 -->
        <div class="post_body">
            <p>{{ post.body }}</p>
        </div>

        <!-- 수정과 삭제 버튼 -->

        {% endif %}
        {% if user == post.user.user %}
        <div class="edit_buttons">
            <div><button type="button" id="edit_button" class="btn"
                    onclick=location.href="{% url 'posts:edit' post.id %}">수정</button></div>
            <div><button type="button" id="edit_button" class="btn"
                    onclick=location.href="{% url 'posts:delete' post.id %}">삭제</button></div>
        </div>
        {% endif %}
    </div>


    <!-- 댓글 생성 및 보여주기 -->
    <div class="row" id="comment_info">
        <div class="comment_container">
            <form class="comment_form" method="POST" action="{% url 'posts:comment' post.id %}">
                {% csrf_token %}
                <label id="secret_check"><input id="secret_checkbox" type="checkbox" name="secret_comment"
                        value="True">작성자에게 귓속말하기</label>
                <textarea name="content" id="" cols="50" rows="5" placeholder="댓글을 남겨주세요"></textarea>
                <button class="btn btn-secondary" id="comment_button" type="submit">댓글 달기</button>
            </form>
        </div>

        <!-- 댓글 표시 -->
        <div class="post_comment">
            {% for comment in post.post_comments.all %}
            <!-- 비밀댓글 체크 X -->
            {% if comment.secret == False %}
            <p>{{ comment.author }} <span>{{ comment.created_at|date:'Y-m-d H:i:s' }}</span></p>
            <p>{{ comment.content }}</p>
            <!-- 글 작성자라면 -->
            {% elif comment.secret == True and user == post.user.user %}
            <p id="secret_index">(귓속말)</p>
            <p>{{ comment.author }} <span>{{ comment.created_at|date:'Y-m-d H:i:s' }}</span></p>
            <p>{{ comment.content }}</p>
            <!-- 댓글 작성자라면 -->
            {% elif comment.secret == True and user == comment.author.user %}
            <p>{{ comment.author }} <span>{{ comment.created_at|date:'Y-m-d H:i:s' }}</span></p>
            <p>{{ comment.content }}</p>
            <!-- 비밀댓글 체크 O -->
            {% elif comment.secret == True %}
            <p id="secret_index">(귓속말)</p>
            <p>{{ comment.author }} <span>{{ comment.created_at|date:'Y-m-d H:i:s' }}</span></p>
            <p style="color: #A29F9F; font-weight: 500;">작성자에게만 보이는 댓글입니다.</p>
            {% endif %}
            <!-- 댓글 삭제 버튼 -->
            {% if user == comment.author.user %}
            <a href="{% url 'posts:comment_delete' post.id comment.id %}"><button id="comment_delete" type="submit"
                    name="delete">삭제</button></a>
            {% endif %}
            <hr>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'posts/edit_style.css' %}">
{% endblock %}

{% block content %}
<div class="col-lg-12 col-md-12 col-sm-12" id="edit_container">
    <h1 id="edit_title">글 수정하기</h1>

    <!-- 글 수정 div -->
    <div class="edit_container"> 
        <form method="POST" action="{% url 'posts:edit' post.id %}">
            {% csrf_token %}

            <!-- 지역 선택 및 등록 버튼 -->
            <div>
                <!-- <select id="select_photospot" name="photospot" required>
                    <option value="" disabled selected>{{ post.location }}</option>
                    {% for travel in travels %}
                    <option value="{{ travel.title }}">{{ travel.title }}</option>
                    {% endfor %}
                </select> -->
            
                <button id="edit_submit" type="submit">수정</button>
            </div>

            <!-- 글 수정 정보 받기 -->
            <div class="mb-4">
                <input type="text" class="form-control" id="title" name="title" value="{{ post.title }}">
            </div>
            <div class="mb-3">
                <textarea class="form-control" id="body" rows="5" name="body">{{ post.body }}</textarea>
            </div>
            <!-- <div class="mb-3">
                <label for="due">기한 설정하기</label>
                <input type="date" class="form-control" id="due" name="due" style="margin-top: 10px;">
            </div> -->

        </form>
    </div>    
</div>
{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}
{% load post_filter %}
{% load static %}
 
 
 
{% block style %}
<link rel="stylesheet" href="{% static 'posts_style.css' %}">
{% endblock %}
 
 
 
{% block content %}
<div class="posts-page">
    <div class="posts-top-bar">
        <div>
            <!-- 글쓰기 버튼 -->
            <button type="button" id="posts-b2" class="btn btn-secondary" onclick=location.href="{% url 'posts:create' %}">글쓰기</button>
            <!-- 검색창 -->
        </div>
        <div>
                <form class="posts-button" method="GET" action="">
                    <input class="form-control" type="search" name="query" placeholder="{{ q }}">
                    <button id="posts-b1" class="btn btn-secondary" type="submit" ><p>검색하기</p></button>
                </form>
        </div>
    </div>

    <!-- 게시판 -->
    <div class="posts_text1">함께 <span class="posts_text2">스팟온!</span>할 친구를 찾아보세요.</div>

    <div class="posts_list">
        <table class="table" id="table_container">   
            <thead>
                <tr>
                    <th class="posts_head" scope="col">#</th>
                    <th class="posts_head" id="posts_title" scope="col">제목</th>
                    <!-- <th class="posts_head" scope="col"><i class="fas fa-map-marker-alt"></i></th> -->
                    <th class="posts_head" scope="col"><i class="fas fa-user"></i></th>
                    <th class="posts_head" scope="col">작성일</th>
                    <!-- <th class="posts_head" scope="col">Due</th>    -->
                </tr>
            </thead>
        
            <tbody>
                {% if not q %}
                    {% for post in posts_page %}
                    <tr>
                        <td>{{ posts_page.paginator.count|sub:posts_page.start_index|sub:forloop.counter0|add:1 }}</td>
                        <td><a id="post_detail_a" href="{% url 'posts:detail' post.id %}">{{ post.title }} 
                            {% if post.post_comments.count %}   
                                ({{ post.post_comments.count }})    
                            {% endif %}
                            </a></td>
                        <!-- <td>{{ post.location }}</td> -->
                        <td>{{ post.user }}</td>
                        <td>{{ post.created_at|date:'Y-m-d' }}</td>
                        <!-- <td>{{ post.due|date:'Y-m-d' }}</td>   -->
                    </tr> 
                    {% endfor %}  
                {% else %}
                    {% for post in posts_page %}
                    <tr>
                        <td></td>
                        <td><a id="post_detail_a" href="{% url 'posts:detail' post.id %}">{{ post.title }} 
                            {% if post.post_comments.count %}   
                                ({{ post.post_comments.count }})    
                            {% endif %}
                            </a></td>
                        <!-- <td>{{ post.location }}</td> -->
                        <td>{{ post.user }}</td>
                        <td>{{ post.created_at|date:'Y-m-d' }}</td>
                        <!-- <td>{{ post.due|date:'Y-m-d' }}</td>   -->
                    </tr> 
                    {% endfor %}
                {% endif %}      
            </tbody>
        </table>


    <!-- 페이지네이터 코드 -->
        <div>
            <nav aria-label="Page navigation example" id="paginator_container">
                <ul class="pagination">
                <!-- 이전 페이지 버튼 -->    
                    {% if posts_page.has_previous %}    
                    <li class="page-item"><a class="page-link" href="?page={{ posts_page.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="?page=1" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    {% endif %}
                
                <!-- 페이지 숫자 나타내기 -->    
                    {% for i in page_range %}
                    {% if i == posts_page.number %}  
                    <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}
                
                <!-- 다음 페이지 버튼 -->    
                    {% if posts_page.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ posts_page.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="?page={{ posts_page.paginator.num_pages }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>



</div>
{% endblock %}